### ISSUE TITLE
Program crashuje gdy wyłączamy go za pomocą konsoli

### ISSUE THREAD

**Issue by Michaleczeq** [MinusPL/VirtualCargo#3]
Program wywala błąd, gdy go zamykamy używając konsoli.

**Comment by MinusPL** [comment]
Wina konsoli, Prawdopodobnie błąd zostanie wyeliminowany wkrótce

**Comment by MinusPL** [comment]
Edit: Błąd zlokalizowany, konsola jest w porządku.

**Comment by MinusPL** [comment]
Błąd naprawiony w nadchodzącej wersji 0.2
